{{- if .Values.plugins.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: {{ .Release.Namespace }}
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: {{ .Values.scheduler.leaderElect }}
      resourceNamespace: {{ .Release.Namespace }}
      resourceName: {{ .Values.scheduler.name }}
    profiles:
    # Compose all plugins in one profile
    - schedulerName: {{ .Values.scheduler.name }}
      {{- $percentageOfNodesToScore := default .Values.scheduler.percentageOfNodesToScore .Values.percentageOfNodesToScore }}
      {{- if $percentageOfNodesToScore }}
      percentageOfNodesToScore: {{ $percentageOfNodesToScore }}
      {{- end }}
      plugins:
        multiPoint:
          enabled:
          {{- range $.Values.plugins.enabled }}
          - name: {{ title . }}
          {{- end }}
          disabled:
          {{- range $.Values.plugins.disabled }}
          - name: {{ title . }}
          {{- end }}
        {{- $extensionPoints := tuple "preEnqueue" "queueSort" "preFilter" "filter" "postFilter" "preScore" "score" "reserve" "permit" "preBind" "bind" "postBind" "placementGenerate" "placementScore" "podGroupPostFilter" }}
        {{- range $ep := $extensionPoints }}
        {{- with (index $.Values.plugins $ep) }}
        {{- if or .enabled .disabled }}
        {{ $ep }}:
          {{- with .enabled }}
          enabled:
          {{- range . }}
          {{- if kindIs "map" . }}
          - name: {{ .name }}
            {{- if .weight }}
            weight: {{ .weight }}
            {{- end }}
          {{- else }}
          - name: {{ . }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- with .disabled }}
          disabled:
          {{- range . }}
          {{- if kindIs "map" . }}
          - name: {{ .name }}
          {{- else }}
          - name: {{ . }}
          {{- end }}
          {{- end }}
          {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
      {{- if $.Values.pluginConfig }}
      pluginConfig: {{ toYaml $.Values.pluginConfig | nindent 6 }}
      {{- end }}

  {{- /* TODO: wire CRD installation with enabled plugins. */}}
{{- end }}
